# Generated by Django 3.1.7 on 2021-04-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210417_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_can_pause',
        ),
        migrations.RemoveField(
            model_name='room',
            name='votes_to_skip',
        ),
        migrations.AddField(
            model_name='room',
            name='answer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='hint',
            field=models.CharField(default='', max_length=50),
        ),
    ]
